### ISSUE TITLE
Issue in Flutter 3.16.0

### ISSUE THREAD

**Issue by Hassan763** [AhmedAbdoElhawary/image_picker_plus#79]
Can you please provide the solution to resolve this issue

<img width="1792" alt="Screenshot 2023-12-07 at 11 29 44 AM" src="https://github.com/AhmedAbdoElhawary/image_picker_plus/assets/61411612/800730d3-0742-467b-8c69-6a87d7ef1b4c">

**Comment by YeLwinOo-Steve** [comment]
@Hassan763 As a quick fix, you can use like this. I've opened a pull request that solves this issue. As this is is a severe issue, hope that it'll get merged.

 ```
 image_picker_plus:
    git:
      url: https://github.com/YeLwinOo-Steve/image_picker_plus.git
      ref: main

```
